### ISSUE TITLE
Calculation of slope with VCTFPW

### ISSUE THREAD

**Issue by soner90** [mannkendall/R#16]
Not sure if this is a bug or not, but regarding the calculation of slope based on VCTFPW prewhitened data I get somehwat "wrong" results compared to all other PW methods. 
In my case, slope value is positive based on other prewhitened and non-prewhitened data. Only for VCTFPW slope value is negative which makes no sense. In literature (Wang et al. 2015) the first step in calculation consists of removing the trend from the original time series. 
In your code (R/prewhite.R line 81) you also include variable epoch.time in this first step.
Using "dataDetrend.or <- data - b0.or" instead of "dataDetrend.or <- data - b0.or * c(epoch.time - epoch.time[1])" seems to result in "correct" (positive as derived by other PW methods) slope value in my example.

**Comment by mcollaudcoen** [comment]
The code line R/prewhite.R line 81) is right and should include this time variable that has to multiply the slope to detrend the time series.
First, is the detected trend statistically significant ? if not (remember that PW and TFPW-Y have a lot of false positives, rely on the ss of TFPW-WS), it doesn't matter if the slope is positive or negative, because it is just statistically not different from zero. 
If the trend is ss, do you have the same behavior for other timeseries ? Can you describe me your time series ?

**Comment by soner90** [comment]
Thanks a lot for your quick response! Sorry my mistake, you are right, the problem is caused by the trend not being ss. For one example TFPW-Y and TFPW-WS indicate ss trend, but not PW. But I did not check PW in this case. So now I only use VCTFPW if max(TFPW-Y, PW) & TFPW-WS is ss.
